# Climate Change Data

**Data from**: https://www.kaggle.com/datasets/sevgisarac/temperature-change (Attribution 3.0 IGO, CC BY 3.0 IGO)
 
**Source**: http://www.fao.org/faostat/en/#data/ET/metadata

**Acknowledgements** (as in Kaggle)

Documentation on methodology: Details on the methodology can be accessed at the Related Documents section of the Temperature Change (ET) domain in the Agri-Environmental Indicators section of FAOSTAT.

Quality documentation: For more information on the methods, coverage, accuracy and limitations of the Temperature Change dataset please refer to the NASA GISTEMP website: https://data.giss.nasa.gov/gistemp/

## First exploratory analysis

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib as plt
import plotly.express as px

In [2]:
db1 = pd.read_csv('../raw_data/climate data/Environment_Temperature_change_E_All_Data_NOFLAG.csv',  encoding='latin-1')
db1

,Area Code,Area,Months Code,Months,Element Code,Element,Unit,Y1961,Y1962,Y1963,...,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019
0,2,Afghanistan,7001,January,7271,Temperature change,°C,0.777,0.062,2.744,...,3.601,1.179,-0.583,1.233,1.755,1.943,3.416,1.201,1.996,2.951
1,2,Afghanistan,7001,January,6078,Standard Deviation,°C,1.950,1.950,1.950,...,1.950,1.950,1.950,1.950,1.950,1.950,1.950,1.950,1.950,1.950
2,2,Afghanistan,7002,February,7271,Temperature change,°C,-1.743,2.465,3.919,...,1.212,0.321,-3.201,1.494,-3.187,2.699,2.251,-0.323,2.705,0.086
3,2,Afghanistan,7002,February,6078,Standard Deviation,°C,2.597,2.597,2.597,...,2.597,2.597,2.597,2.597,2.597,2.597,2.597,2.597,2.597,2.597
4,2,Afghanistan,7003,March,7271,Temperature change,°C,0.516,1.336,0.403,...,3.390,0.748,-0.527,2.246,-0.076,-0.497,2.296,0.834,4.418,0.234
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9651,5873,OECD,7018,JunJulAug,6078,Standard Deviation,°C,0.247,0.247,0.247,...,0.247,0.247,0.247,0.247,0.247,0.247,0.247,0.247,0.247,0.247
9652,5873,OECD,7019,SepOctNov,7271,Temperature change,°C,0.036,0.461,0.665,...,0.958,1.106,0.885,1.041,0.999,1.670,1.535,1.194,0.581,1.233
9653,5873,OECD,7019,SepOctNov,6078,Standard Deviation,°C,0.378,0.378,0.378,...,0.378,0.378,0.378,0.378,0.378,0.378,0.378,0.378,0.378,0.378
9654,5873,OECD,7020,Meteorological year,7271,Temperature change,°C,0.165,-0.009,0.134,...,1.246,0.805,1.274,0.991,0.811,1.282,1.850,1.349,1.088,1.297
9655,5873,OECD,7020,Meteorological year,6078,Standard Deviation,°C,0.260,0.260,0.260,...,0.260,0.260,0.260,0.260,0.260,0.260,0.260,0.260,0.260,0.260

In [3]:
db2 = pd.read_csv('../raw_data/climate data/FAOSTAT_data_1-10-2022.csv')
db2

,Domain Code,Domain,Area Code (FAO),Area,Element Code,Element,Months Code,Months,Year Code,Year,Unit,Value,Flag,Flag Description
0,ET,Temperature change,2,Afghanistan,7271,Temperature change,7001,January,1961,1961,?C,0.746,Fc,Calculated data
1,ET,Temperature change,2,Afghanistan,7271,Temperature change,7001,January,1962,1962,?C,0.009,Fc,Calculated data
2,ET,Temperature change,2,Afghanistan,7271,Temperature change,7001,January,1963,1963,?C,2.695,Fc,Calculated data
3,ET,Temperature change,2,Afghanistan,7271,Temperature change,7001,January,1964,1964,?C,-5.277,Fc,Calculated data
4,ET,Temperature change,2,Afghanistan,7271,Temperature change,7001,January,1965,1965,?C,1.827,Fc,Calculated data
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229920,ET,Temperature change,181,Zimbabwe,7271,Temperature change,7020,Meteorological year,2016,2016,?C,1.470,Fc,Calculated data
229921,ET,Temperature change,181,Zimbabwe,7271,Temperature change,7020,Meteorological year,2017,2017,?C,0.443,Fc,Calculated data
229922,ET,Temperature change,181,Zimbabwe,7271,Temperature change,7020,Meteorological year,2018,2018,?C,0.747,Fc,Calculated data
229923,ET,Temperature change,181,Zimbabwe,7271,Temperature change,7020,Meteorological year,2019,2019,?C,1.359,Fc,Calculated data
229924,ET,Temperature change,181,Zimbabwe,7271,Temperature change,7020,Meteorological year,2020,2020,?C,0.820,Fc,Calculated data

In [4]:
db3 = pd.read_csv('/Users/alessandrasellini/code/projects/snake_conservation_status/raw_data/climate data/FAOSTAT_data_11-24-2020.csv')
db3

,Country Code,Country,M49 Code,ISO2 Code,ISO3 Code,Start Year,End Year
0,2,Afghanistan,4.0,AF,AFG,NaN,NaN
1,5100,Africa,2.0,NaN,X06,NaN,NaN
2,284,Åland Islands,248.0,NaN,ALA,NaN,NaN
3,3,Albania,8.0,AL,ALB,NaN,NaN
4,4,Algeria,12.0,DZ,DZA,NaN,NaN
...,...,...,...,...,...,...,...
316,246,Yemen Ar Rp,886.0,NaN,NaN,NaN,NaN
317,247,Yemen Dem,720.0,NaN,NaN,NaN,NaN
318,248,Yugoslav SFR,890.0,NaN,NaN,NaN,1991.0
319,251,Zambia,894.0,ZM,ZMB,NaN,NaN
320,181,Zimbabwe,716.0,ZW,ZWE,NaN,NaN

### Exploration of first dataset

In [5]:
db1.columns

Index(['Area Code', 'Area', 'Months Code', 'Months', 'Element Code', 'Element',
       'Unit', 'Y1961', 'Y1962', 'Y1963', 'Y1964', 'Y1965', 'Y1966', 'Y1967',
       'Y1968', 'Y1969', 'Y1970', 'Y1971', 'Y1972', 'Y1973', 'Y1974', 'Y1975',
       'Y1976', 'Y1977', 'Y1978', 'Y1979', 'Y1980', 'Y1981', 'Y1982', 'Y1983',
       'Y1984', 'Y1985', 'Y1986', 'Y1987', 'Y1988', 'Y1989', 'Y1990', 'Y1991',
       'Y1992', 'Y1993', 'Y1994', 'Y1995', 'Y1996', 'Y1997', 'Y1998', 'Y1999',
       'Y2000', 'Y2001', 'Y2002', 'Y2003', 'Y2004', 'Y2005', 'Y2006', 'Y2007',
       'Y2008', 'Y2009', 'Y2010', 'Y2011', 'Y2012', 'Y2013', 'Y2014', 'Y2015',
       'Y2016', 'Y2017', 'Y2018', 'Y2019'],
      dtype='object')

In [6]:
db1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9656 entries, 0 to 9655
Data columns (total 66 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Area Code     9656 non-null   int64
 1   Area          9656 non-null   object
 2   Months Code   9656 non-null   int64
 3   Months        9656 non-null   object
 4   Element Code  9656 non-null   int64
 5   Element       9656 non-null   object
 6   Unit          9656 non-null   object
 7   Y1961         8287 non-null   float64
 8   Y1962         8322 non-null   float64
 9   Y1963         8294 non-null   float64
 10  Y1964         8252 non-null   float64
 11  Y1965         8281 non-null   float64
 12  Y1966         8364 non-null   float64
 13  Y1967         8347 non-null   float64
 14  Y1968         8345 non-null   float64
 15  Y1969         8326 non-null   float64
 16  Y1970         8308 non-null   float64
 17  Y1971         8303 non-null   float64
 18  Y1972         8323 non-null   float64
 19  Y1973         8394 non-null   float64
 20  Y1974         8374 non-null   float64
 21  Y1975         8280 non-null   float64
 22  Y1976         8209 non-null   float64
 23  Y1977         8257 non-null   float64
 24  Y1978         8327 non-null   float64
 25  Y1979         8290 non-null   float64
 26  Y1980         8283 non-null   float64
 27  Y1981         8276 non-null   float64
 28  Y1982         8237 non-null   float64
 29  Y1983         8205 non-null   float64
 30  Y1984         8259 non-null   float64
 31  Y1985         8216 non-null   float64
 32  Y1986         8268 non-null   float64
 33  Y1987         8284 non-null   float64
 34  Y1988         8273 non-null   float64
 35  Y1989         8257 non-null   float64
 36  Y1990         8239 non-null   float64
 37  Y1991         8158 non-null   float64
 38  Y1992         8354 non-null   float64
 39  Y1993         8315 non-null   float64
 40  Y1994         8373 non-null   float64
 41  Y1995         8409 non-null   float64
 42  Y1996         8439 non-null   float64
 43  Y1997         8309 non-null   float64
 44  Y1998         8370 non-null   float64
 45  Y1999         8324 non-null   float64
 46  Y2000         8342 non-null   float64
 47  Y2001         8241 non-null   float64
 48  Y2002         8312 non-null   float64
 49  Y2003         8390 non-null   float64
 50  Y2004         8415 non-null   float64
 51  Y2005         8424 non-null   float64
 52  Y2006         8503 non-null   float64
 53  Y2007         8534 non-null   float64
 54  Y2008         8475 non-null   float64
 55  Y2009         8419 non-null   float64
 56  Y2010         8435 non-null   float64
 57  Y2011         8437 non-null   float64
 58  Y2012         8350 non-null   float64
 59  Y2013         8427 non-null   float64
 60  Y2014         8377 non-null   float64
 61  Y2015         8361 non-null   float64
 62  Y2016         8348 non-null   float64
 63  Y2017         8366 non-null   float64
 64  Y2018         8349 non-null   float64
 65  Y2019         8365 non-null   float64
dtypes: float64(59), int64(3), object(4)
memory usage: 4.9+ MB

In [7]:
db1.value_counts('Unit')

Unit
°C    9656
dtype: int64

In [8]:
db1.value_counts('Area').sort_values()

Area
Afghanistan                         34
Annex I countries                   34
Asia                                34
Aruba                               34
Armenia                             34
                                    ..
Zambia                              34
Western Asia                        34
Saint Vincent and the Grenadines    34
Western Sahara                      34
Zimbabwe                            34
Length: 284, dtype: int64

In [9]:
temp_record = db1.drop(columns=['Area Code', 'Months Code', 'Element Code', 'Unit'])
temp_record

,Area,Months,Element,Y1961,Y1962,Y1963,Y1964,Y1965,Y1966,Y1967,...,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019
0,Afghanistan,January,Temperature change,0.777,0.062,2.744,-5.232,1.868,3.629,-1.432,...,3.601,1.179,-0.583,1.233,1.755,1.943,3.416,1.201,1.996,2.951
1,Afghanistan,January,Standard Deviation,1.950,1.950,1.950,1.950,1.950,1.950,1.950,...,1.950,1.950,1.950,1.950,1.950,1.950,1.950,1.950,1.950,1.950
2,Afghanistan,February,Temperature change,-1.743,2.465,3.919,-0.202,-0.096,3.397,0.296,...,1.212,0.321,-3.201,1.494,-3.187,2.699,2.251,-0.323,2.705,0.086
3,Afghanistan,February,Standard Deviation,2.597,2.597,2.597,2.597,2.597,2.597,2.597,...,2.597,2.597,2.597,2.597,2.597,2.597,2.597,2.597,2.597,2.597
4,Afghanistan,March,Temperature change,0.516,1.336,0.403,1.659,-0.909,-0.069,-0.759,...,3.390,0.748,-0.527,2.246,-0.076,-0.497,2.296,0.834,4.418,0.234
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9651,OECD,JunJulAug,Standard Deviation,0.247,0.247,0.247,0.247,0.247,0.247,0.247,...,0.247,0.247,0.247,0.247,0.247,0.247,0.247,0.247,0.247,0.247
9652,OECD,SepOctNov,Temperature change,0.036,0.461,0.665,-0.157,-0.203,-0.295,0.321,...,0.958,1.106,0.885,1.041,0.999,1.670,1.535,1.194,0.581,1.233
9653,OECD,SepOctNov,Standard Deviation,0.378,0.378,0.378,0.378,0.378,0.378,0.378,...,0.378,0.378,0.378,0.378,0.378,0.378,0.378,0.378,0.378,0.378
9654,OECD,Meteorological year,Temperature change,0.165,-0.009,0.134,-0.190,-0.385,-0.166,-0.090,...,1.246,0.805,1.274,0.991,0.811,1.282,1.850,1.349,1.088,1.297
9655,OECD,Meteorological year,Standard Deviation,0.260,0.260,0.260,0.260,0.260,0.260,0.260,...,0.260,0.260,0.260,0.260,0.260,0.260,0.260,0.260,0.260,0.260

In [10]:
temp_aus = temp_record[(temp_record['Area'].str.contains('Aus')) & (temp_record['Area'] != 'Austria')]
temp_aus

,Area,Months,Element,Y1961,Y1962,Y1963,Y1964,Y1965,Y1966,Y1967,...,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019
408,Australia,January,Temperature change,0.287,-0.088,-0.652,-0.227,-0.076,-0.206,0.115,...,0.877,1.078,0.284,1.978,1.237,0.405,0.883,1.065,1.494,2.727
409,Australia,January,Standard Deviation,0.610,0.610,0.610,0.610,0.610,0.610,0.610,...,0.610,0.610,0.610,0.610,0.610,0.610,0.610,0.610,0.610,0.610
410,Australia,February,Temperature change,-0.002,-0.033,-0.078,-0.556,1.239,-0.145,-0.503,...,1.069,0.068,-0.029,1.045,0.382,1.930,1.290,0.739,0.999,1.456
411,Australia,February,Standard Deviation,0.574,0.574,0.574,0.574,0.574,0.574,0.574,...,0.574,0.574,0.574,0.574,0.574,0.574,0.574,0.574,0.574,0.574
412,Australia,March,Temperature change,0.238,-0.430,0.366,0.104,-0.201,-0.029,-1.477,...,0.425,-0.679,-0.765,0.877,0.913,0.848,1.763,1.682,1.066,1.899
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9243,Australia and New Zealand,JunJulAug,Standard Deviation,0.448,0.448,0.448,0.448,0.448,0.448,0.448,...,0.448,0.448,0.448,0.448,0.448,0.448,0.448,0.448,0.448,0.448
9244,Australia and New Zealand,SepOctNov,Temperature change,0.784,0.186,0.110,-0.363,0.629,-0.525,0.579,...,0.046,0.562,1.240,1.719,1.773,1.836,0.340,1.380,1.218,1.498
9245,Australia and New Zealand,SepOctNov,Standard Deviation,0.527,0.527,0.527,0.527,0.527,0.527,0.527,...,0.527,0.527,0.527,0.527,0.527,0.527,0.527,0.527,0.527,0.527
9246,Australia and New Zealand,Meteorological year,Temperature change,0.136,0.139,-0.122,-0.036,0.108,-0.237,-0.095,...,0.642,0.192,0.268,1.435,1.119,1.035,1.144,1.101,1.114,1.413
9247,Australia and New Zealand,Meteorological year,Standard Deviation,0.325,0.325,0.325,0.325,0.325,0.325,0.325,...,0.325,0.325,0.325,0.325,0.325,0.325,0.325,0.325,0.325,0.325

In [11]:
temp_aus.value_counts('Months')

Months
April                  4
March                  4
September              4
October                4
November               4
Meteorological year    4
May                    4
MarAprMay            4
JunJulAug            4
August                 4
June                   4
July                   4
January                4
February               4
DecJanFeb            4
December               4
SepOctNov            4
dtype: int64

In [12]:
metyear_aus = temp_aus[(temp_aus['Months'] == 'Meteorological year') & (temp_aus['Element'] == 'Temperature change')]
metyear_aus

,Area,Months,Element,Y1961,Y1962,Y1963,Y1964,Y1965,Y1966,Y1967,...,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019
440,Australia,Meteorological year,Temperature change,0.151,0.123,-0.114,-0.022,0.127,-0.238,-0.092,...,0.644,0.176,0.273,1.450,1.139,1.051,1.142,1.117,1.112,1.423
9246,Australia and New Zealand,Meteorological year,Temperature change,0.136,0.139,-0.122,-0.036,0.108,-0.237,-0.095,...,0.642,0.192,0.268,1.435,1.119,1.035,1.144,1.101,1.114,1.413

In [13]:
metyear_aus = metyear_aus.set_index("Area")
metyear_aus

,Months,Element,Y1961,Y1962,Y1963,Y1964,Y1965,Y1966,Y1967,Y1968,...,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019
Area,,,,,,,,,,,,,,,,,,,,,
Australia,Meteorological year,Temperature change,0.151,0.123,-0.114,-0.022,0.127,-0.238,-0.092,-0.206,...,0.644,0.176,0.273,1.450,1.139,1.051,1.142,1.117,1.112,1.423
Australia and New Zealand,Meteorological year,Temperature change,0.136,0.139,-0.122,-0.036,0.108,-0.237,-0.095,-0.202,...,0.642,0.192,0.268,1.435,1.119,1.035,1.144,1.101,1.114,1.413

In [14]:
australia = pd.DataFrame(metyear_aus.loc["Australia"])
australia = australia.drop(index=['Months', 'Element']).reset_index()
australia = australia.rename(columns={"index": "Year", "Australia": "Temperature Change"})
australia

     Year Temperature Change
0   Y1961              0.151
1   Y1962              0.123
2   Y1963             -0.114
3   Y1964             -0.022
4   Y1965              0.127
5   Y1966             -0.238
6   Y1967             -0.092
7   Y1968             -0.206
8   Y1969              0.112
9   Y1970              0.002
10  Y1971              -0.04
11  Y1972              0.099
12  Y1973              0.858
13  Y1974             -0.345
14  Y1975              0.061
15  Y1976               -0.5
16  Y1977               0.19
17  Y1978              0.078
18  Y1979              0.368
19  Y1980              0.862
20  Y1981              0.456
21  Y1982              0.158
22  Y1983              0.605
23  Y1984             -0.191
24  Y1985              0.296
25  Y1986              0.329
26  Y1987              0.304
27  Y1988              0.906
28  Y1989              0.109
29  Y1990              0.495
30  Y1991              0.778
31  Y1992              0.215
32  Y1993              0.415
33  Y1994              0.166
34  Y1995              0.347
35  Y1996              0.522
36  Y1997              0.317
37  Y1998              1.022
38  Y1999              0.542
39  Y2000              0.122
40  Y2001               0.32
41  Y2002              0.706
42  Y2003               0.79
43  Y2004              0.671
44  Y2005              1.144
45  Y2006              0.643
46  Y2007              0.864
47  Y2008              0.553
48  Y2009              0.968
49  Y2010              0.644
50  Y2011              0.176
51  Y2012              0.273
52  Y2013               1.45
53  Y2014              1.139
54  Y2015              1.051
55  Y2016              1.142
56  Y2017              1.117
57  Y2018              1.112
58  Y2019              1.423

In [15]:
australia['Year'] = australia['Year'].str.strip('Y')
australia

    Year Temperature Change
0   1961              0.151
1   1962              0.123
2   1963             -0.114
3   1964             -0.022
4   1965              0.127
5   1966             -0.238
6   1967             -0.092
7   1968             -0.206
8   1969              0.112
9   1970              0.002
10  1971              -0.04
11  1972              0.099
12  1973              0.858
13  1974             -0.345
14  1975              0.061
15  1976               -0.5
16  1977               0.19
17  1978              0.078
18  1979              0.368
19  1980              0.862
20  1981              0.456
21  1982              0.158
22  1983              0.605
23  1984             -0.191
24  1985              0.296
25  1986              0.329
26  1987              0.304
27  1988              0.906
28  1989              0.109
29  1990              0.495
30  1991              0.778
31  1992              0.215
32  1993              0.415
33  1994              0.166
34  1995              0.347
35  1996              0.522
36  1997              0.317
37  1998              1.022
38  1999              0.542
39  2000              0.122
40  2001               0.32
41  2002              0.706
42  2003               0.79
43  2004              0.671
44  2005              1.144
45  2006              0.643
46  2007              0.864
47  2008              0.553
48  2009              0.968
49  2010              0.644
50  2011              0.176
51  2012              0.273
52  2013               1.45
53  2014              1.139
54  2015              1.051
55  2016              1.142
56  2017              1.117
57  2018              1.112
58  2019              1.423

## Data Visualization

In [20]:
fig = px.line(australia, x="Year", y="Temperature Change")
fig.show()